name: Build Desktop Binaries

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Code-Checkout
        uses: actions/checkout@v4

      - name: Build Linux App Image
        run: ./gradlew :desktopApp:packageAppImage

      - name: Move App Image for Upload
        run: |
          mkdir -p upload
          cp -r 'desktopApp/build/compose/binaries/main/app/Music Manager' upload/

      - name: Upload Linux
        uses: actions/upload-artifact@v7
        with:
          name: Music Manager
          path: upload/*
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Code-Checkout
        uses: actions/checkout@v4

      - name: Build Windows Msi
        run: ./gradlew :desktopApp:packageMsi

      - name: Move App Image for Upload
        run: |
          mkdir -p upload
          cp -r 'desktopApp/build/compose/binaries/main/msi/*' upload/

      - name: Upload Windows Msi
        uses: actions/upload-artifact@v7
        with:
          name: Music Manager.msi
          path: upload/*.msi
          archive: false
